#:schema /home/chrono/Dev/dotfiles-manager/schemas/config.schema.json

[general]
repo_path = "~/.dotfiles"
backup_dir = "~/.dotfiles-backups"
current_profile = "default"
symlink_resolution = "auto"

[tools.cursor]
files = [{ repo = "cursor/settings.json", dest = ".config/Cursor/User/settings.json" }, { repo = "cursor/keybindings.json", dest = ".config/Cursor/User/keybindings.json" }, { repo = "cursor/argv.json", dest = ".cursor/argv.json" },
]

[tools.fonts]
files = [{ repo = "fonts/SF-Mono-Regular.otf", dest = ".local/share/fonts/SF-Mono-Regular.otf" }, { repo = "fonts/SFHello-Regular.otf", dest = ".local/share/fonts/SFHello-Regular.otf" }, { repo = "fonts/SFMonoNerdFont-Regular.otf", dest = ".local/share/fonts/SFMonoNerdFont-Regular.otf" }, { repo = "fonts/JetBrainsMonoNerdFont-Regular.ttf", dest = ".local/share/fonts/JetBrainsMonoNerdFont-Regular.ttf" },
]

[tools.waybar]
files = [{ repo = "waybar/config", dest = ".config/waybar/config" }, { repo = "waybar/style.css", dest = ".config/waybar/style.css" },
]

[tools.zsh]
files = [{ repo = "zsh/.zshrc", dest = ".zshrc" },
]

[tools.sway]
files = [{ repo = "sway/config", dest = ".config/sway/config" }, { repo = "sway/config.d/60-bindings-screenshot.conf", dest = ".config/sway/config.d/60-bindings-screenshot.conf" }, { repo = "sway/config.d/90-bar.conf", dest = ".config/sway/config.d/90-bar.conf" },
]

[tools.starship]
files = [{ repo = "starship/starship.toml", dest = ".config/starship.toml" },
]

[tools.alacritty]
files = [{ repo = "alacritty/alacritty.toml", dest = "..config/alacritty/alacritty.toml" },
]
